apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      # nodeSelector:
      #   fleet : A
      containers:
        - name: client
          image: bobmorane/fl-client:v1.0
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: http_proxy
              value: "http://$(NODE_NAME).sop.renault.fr:911"
